version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Running Vite build...
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully on `date`
artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: yes
